CREATE TABLE IF NOT EXISTS DEV_SOME_DB.BMT.STG_ACCOUNTS (
    ACCOUNT_ID VARCHAR(10) NOT NULL COMMENT 'account identifier' 
    , PROGRAM_ID VARCHAR(18) NOT NULL COMMENT 'program identifier'
    , VETTED VARCHAR(20) NOT NULL COMMENT 'account and program vetting status'
    , LOAD_TS TIMESTAMP_NTZ(3) DEFAULT SYSDATE()::TIMESTAMP_NTZ(3) COMMENT 'load timestamp'
);