USE ROLE USERADMIN;

CREATE ROLE IF NOT EXISTS DEV_ENG COMMENT = 'This role has have DEV DB full privileges';
CREATE ROLE IF NOT EXISTS PROD_ENG COMMENT = 'This role has have PROD DB full privileges';
CREATE ROLE IF NOT EXISTS ENG COMMENT = 'This role has have DEV and PROD DB full privileges';

SHOW ROLES;

-- Switch over to the SYSADMIN role to create a DEV and PROD db respectively
USE ROLE SYSADMIN;

CREATE DATABASE DEV_SOME_DB;
CREATE DATABASE PROD_SOME_DB;

SHOW DATABASES;

-- Switch to SECURITYADMIN role to grant privileges
USE ROLE SECURITYADMIN;
GRANT USAGE ON WAREHOUSE SNOWFLAKE_LEARNING_WH TO ROLE DEV_ENG;
GRANT ALL PRIVILEGES ON DATABASE DEV_SOME_DB TO ROLE DEV_ENG;
GRANT USAGE ON WAREHOUSE SNOWFLAKE_LEARNING_WH TO ROLE PROD_ENG;
GRANT ALL PRIVILEGES ON DATABASE PROD_SOME_DB TO ROLE PROD_ENG;

SHOW GRANTS TO ROLE DEV_ENG;

GRANT ROLE DEV_ENG TO ROLE ENG;
GRANT ROLE PROD_ENG TO ROLE ENG;

GRANT ROLE ENG TO ROLE SYSADMIN;

-- Change default role for user 'serban' to ENG
USE ROLE USERADMIN;
ALTER USER SERBAN SET DEFAULT_ROLE = ENG;

-- create another user "serban1" with DEV_ENGrole
CREATE USER SERBAN1 PASSWORD = 're@lly tough 1 to crack' DEFAULT_ROLE = DEV_ENG MUST_CHANGE_PASSWORD = FALSE TYPE = PERSON;

DESCRIBE USER SERBAN1;

USE ROLE SECURITYADMIN;
GRANT ROLE DEV_ENG TO USER SERBAN1;

SHOW GRANTS TO USER SERBAN1;